export const GAME_LIST_REQUEST = "GAME_LIST_REQUEST";
export const GAME_LIST_SUCCESS = "GAME_LIST_SUCCESS";
export const GAME_LIST_FAIL = "GAME_LIST_FAIL";

export const GAME_DETAILS_REQUEST = "GAME_DETAILS_REQUEST";
export const GAME_DETAILS_SUCCESS = "GAME_DETAILS_SUCCESS";
export const GAME_DETAILS_FAIL = "GAME_DETAILS_FAIL";
export const GAME_DETAILS_RESET = "GAME_DETAILS_RESET";

export const GAME_DELETE_REQUEST = "GAME_DELETE_REQUEST";
export const GAME_DELETE_SUCCESS = "GAME_DELETE_SUCCESS";
export const GAME_DELETE_FAIL = "GAME_DELETE_FAIL";

export const GAME_UPDATE_REQUEST = "GAME_UPDATE_REQUEST";
export const GAME_UPDATE_SUCCESS = "GAME_UPDATE_SUCCESS";
export const GAME_UPDATE_FAIL = "GAME_UPDATE_FAIL";
export const GAME_UPDATE_RESET = "GAME_UPDATE_RESET";

export const GAME_CREATE_REQUEST = "GAME_CREATE_REQUEST";
export const GAME_CREATE_SUCCESS = "GAME_CREATE_SUCCESS";
export const GAME_CREATE_FAIL = "GAME_CREATE_FAIL";
export const GAME_CREATE_RESET = "GAME_CREATE_RESET";
